---
- name: Playbook 3 - Contrail Backup on all Controllers
  hosts: contrail
  user: heat-admin
  become: true
  tasks:
    - set_fact:

    - name: Execute backup command
      become: yes
      become_user: root
      command: python /usr/lib/python2.7/site-packages/cfgm_common/db_json_exim.py --export-to contrail-db-backup.json
