- name: OpenStack 10 - Overcloud Start Services
  hosts: controller-0
  user: heat-admin
  become: true
  tasks:
    - name: Start Pacemaker
      shell: |
        pcs cluster start --all
  tasks:
    - name: Start OpenStack
      shell: |
        systemctl start openstack-*
  tasks:
    - name: Start Neutron
      shell: |
        systemctl start neutron-*        
  tasks:
    - name: Start HA Proxy
      shell: |
        systemctl start haproxy
  tasks:
    - name: Start HTTPd
      shell: |
        systemctl start httpd
