---
- name: Playbook 5 - Start Contrail on all Controllers
  hosts: contrail
  user: heat-admin
  become: true
  tasks:
    - set_fact:
        bootstrap_node: false
    - name: test ping
      ping:
